name: CI:CD
on:
  push:
    branches: -master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: cloner le code
        uses: actions/checkout@v3

      - name: installer node jobs
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: installer les dépendances
        run: npm install

      #   - name: Lancer les tests
      #     run: npm test

      - name: deployer sur un vps avec ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets. SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ~/workflows || mkdir ~/workflows && cd ~/workflows
            git clone https://github.com/${GITHUB_REPOSITORY} . || git pull
            npm install
            pm2 delete my_appi_node || true
            pm2 start index.js --name my_appi_node 
            pm2 save
            pm2 list
